CREATE TABLE EMPLOYEE (
    empId INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER NOT NULL,
    adress TEXT NOT NULL
);


INSERT INTO EMPLOYEE VALUES (001, 'JULIA', 25, 'MOSCOW');
INSERT INTO EMPLOYEE VALUES (001, 'SVETA', 30, 'TWER');
INSERT INTO EMPLOYEE VALUES (001, 'ALEX', 24, 'TOMSK');
INSERT INTO EMPLOYEE VALUES (001, 'ANATOLIY', 48, 'MOSCOW');
INSERT INTO EMPLOYEE VALUES (001, 'IVAN', 19, 'TULA');


SELECT name FROM EMPLOYEE WHERE adress = 'MOSCOW' AND 18 <= age < 30;